<?php
/**
 * @file
 * Code for the GSB Feature Landing Viewport FPP feature.
 */

include_once 'gsb_feature_landing_viewport_fpp.features.inc';

function gsb_feature_landing_viewport_fpp_form_alter(&$form, &$form_state) {
  dpm($form);
  if ($form['#form_id'] == 'fieldable_panels_panes_fieldable_panels_pane_content_type_edit_form') {
  dpm($form['#form_id']);
    // Get the list of taxonomy terms and set conditions
//    $person_types_index = $form['field_person_type']['und']['#options'];
//    foreach ($person_types_index as $key => $person_type) {
//      if ($person_type == 'MBA Student') {
//
//      } elseif ($person_type == 'Sloan Fellow') {
//
//        $field_condition['field_title_position_single'][] = array('value' => $key);
//
//      } elseif ($person_type == 'PhD Student') {
//
//        $field_condition['field_field_of_study'][] = array('value' => $key);
//
//      } else {
//        drupal_set_message('Selected taxonomy term not defined in gsb_features_voices_ct', 'error');
//      }
//
//    }
//
//    foreach($field_condition as $field => $condition) {
//      $form[$field]['#states'] = [
//        'visible' => [
//          ':input[name="field_person_type[und]"]' => $field_condition[$field],
//        ],
//        'required' => [
//          ':input[name="field_person_type[und]"]' => $field_condition[$field],
//        ]
//      ];
//    }

  }

};
