<?php
/**
 * @file
 * Code for the GSB Feature Landing Viewport FPP feature.
 */

include_once 'gsb_feature_landing_viewport_fpp.features.inc';

function gsb_feature_landing_viewport_fpp_entity_info_alter(&$entity_info) {
  $entity_info['fieldable_panels_pane']['bundles']['landing_viewport'] = array(
    'label' => t('Landing Viewport'),
    'pane category' => t('Homepage Elements'),
    'pane top level' => TRUE, // set to true to make this show as a top level icon
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      // Note that this has all _ replaced with - from the bundle name.
      'real path' => 'admin/structure/fieldable-panels-panes/manage/landing-viewport',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );
}


function gsb_feature_landing_viewport_fpp_preprocess_panels_add_content_modal(&$vars) {
  if (!empty($vars['categories']['root']['content']['Landing Viewport'])) {
    $temp = $vars['categories']['root']['content']['Landing Viewport'];

    unset($vars['categories']['root']['content']['Landing Viewport']);

    $vars['categories']['homepage-elements']['content']['Landing Viewport'] = $temp;
    $vars['categories']['homepage-elements']['content']['Landing Viewport']['category'] = [
      '0' => 'Homepage Elements',
      '1' => '0',
    ];

    unset($vars['categories']['homepage-elements']['content']['Landing Viewport']['top level']);
  }
}

function gsb_feature_landing_viewport_fpp_process_panels_add_content_modal(&$vars) {
  if (!empty($vars['categories']['root']['content']['Landing Viewport'])) {
    $temp = $vars['categories']['root']['content']['Landing Viewport'];

    unset($vars['categories']['root']['content']['Landing Viewport']);

    $vars['categories']['homepage-elements']['content']['Landing Viewport'] = $temp;
    $vars['categories']['homepage-elements']['content']['Landing Viewport']['category'] = [
      '0' => 'Homepage Elements',
      '1' => '0',
    ];
  }
}

/**
 * Implements hook_form_alter().
 */
function gsb_feature_landing_viewport_fpp_form_alter(&$form, &$form_state, $form_id) {
  if (empty($form["#bundle"]) || $form["#bundle"] !== "landing_viewport") {
    return;
  }
  if ($form['#form_id'] == 'fieldable_panels_panes_fieldable_panels_pane_content_type_edit_form') {
    // Get the list of taxonomy terms and set conditions
    drupal_add_css(
      'form#fieldable-panels-panes-fieldable-panels-pane-content-type-edit-form .form-radios span.form-required { display: none !important; }',
      array('group' => 'gsb_theme_admin', 'type' => 'inline')
    );
    unset($form['field_homepage_image_color']['und']['#options']['_none']);
    $media_types = array();
    if (!empty($form['field_image_or_video'])) {
      $media_types = $form['field_image_or_video']['und']['#options'];
    }
    foreach ($media_types as $key => $media_type) {
      if ($media_type == 'Kaltura Video') {

        $field_condition['field_kaltura_video_id'][] = array('value' => $key);
        $field_condition['field_kaltura_video_text'][] = array('value' => $key);

      } elseif ($media_type == 'Video') {

        $field_condition['field_homepage_video_file'][] = array('value' => $key);
        $field_condition['field_homepage_video_text'][] = array('value' => $key);

      } elseif ($media_type == 'Image') {

        $field_condition['field_homepage_image_desktop'][] = array('value' => $key);
        $field_condition['field_homepage_image_tablet'][] = array('value' => $key);
        $field_condition['field_homepage_image_mobile'][] = array('value' => $key);
        $field_condition['field_homepage_image_text'][] = array('value' => $key);
        $field_condition['field_homepage_image_url'][] = array('value' => $key);
        $field_condition['field_homepage_image_color'][] = array('value' => $key);

      } else {
        drupal_set_message('Selected option not defined in gsb_landing_viewport', 'error');
      }
    }

    foreach($field_condition as $field => $condition) {
      $form[$field]['#states'] = [
        'visible' => [
          ':input[name="field_image_or_video[und]"]' => $field_condition[$field],
        ],
        'required' => [
          ':input[name="field_image_or_video[und]"]' => $field_condition[$field],
        ]
      ];
    }

    $form['#validate'][] = 'gsb_feature_landing_viewport_fpp_form_validate';
  }
};

/**
 * Validate handler for gsb_feature_landing_viewport_fpp_form.
 *  - Clear the Kaltura Video Text if Kaltura Video is not the choosen option
 */
function gsb_feature_landing_viewport_fpp_form_validate(&$form, &$form_state) {
  if ($form_state['values']['field_image_or_video']['und'][0]['value'] != 'KalturaVideo') {
    form_set_value($form['field_kaltura_video_text'],array('und' => array(0 => array('value' => ''))),$form_state);
  }
}

function gsb_feature_landing_viewport_fpp_preprocess_fieldable_panels_pane(&$variables) {
    if ($variables['elements']['#bundle'] != 'landing_viewport') {
        return;
    }
    // Add classes based on the color chosen.
    try {
        $wrapper = entity_metadata_wrapper('fieldable_panels_pane', $variables['elements']['#element']);
        $variables['classes_array'][] = 'bg-text-color-' . $wrapper->field_homepage_image_color->value();
    }
    catch (EntityMetadataWrapperException $e) {
        // If the fields are ever missing/renamed, Entity API will throw an
        // exception instead of using watchdog.
        watchdog('gsb_feature_landing_viewport_fpp', 'In @function on line @line: "@message"', array('@function' => __FUNCTION__, '@line' => __LINE__, '@message' => $e->getMessage()), WATCHDOG_ERROR);
    }
}
